# Generated by Django 2.1.15 on 2020-07-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='quantity',
            field=models.CharField(max_length=20),
        ),
    ]
